# Generated by Django 3.1.1 on 2020-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='option1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='option2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='option3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='option4',
            field=models.CharField(max_length=50),
        ),
    ]
